export const mostpopular = [
 
  {
    id: 1,
    title: "Beachfront Villa in Goa",
    location: "Goa, India",
    price: 4500,
    images: ["/goa.jpg"],
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    description: "Enjoy a peaceful beachfront stay with all modern amenities.",
    isWishlisted: false,
     bhk: 3,
  },

  {
    id: 2,
    title: "Luxury Home in Jaipur",
    location: "Jaipur, India",
    price: 3500,
    images: ["/jaipur.jpg"],
    guests: 4,
    bedrooms: 2,
    bathrooms: 2,
    description: "Spacious luxury home near tourist attractions.",
    isWishlisted: false,
     bhk: 2,
  },
  {
    id: 3,
    title: "Rustic Cabin in Manali",
    location: "Manali, India",
    price: 2800,
    images: ["/manali.jpg"],
    guests: 3,
    bedrooms: 1,
    bathrooms: 1,
    description: "Escape to the mountains in this cozy rustic cabin.",
    isWishlisted: false,
     bhk: 2,
  },

  {
    id: 4,
    title: "Heritage Villa in Udaipur",
    location: "Udaipur, India",
    price: 2400,
    images: ["/udaipur.jpg"],
    guests: 4,
    bedrooms: 2,
    bathrooms: 2,
    description: "Enjoy royal charm in this lakeside haveli-style villa.",
    isWishlisted: false,
    bhk: 2,
  },
  {
    id: 5,
    title: "Himalayan Retreat in Shimla",
    location: "Shimla, India",
    price: 1800,
    images: ["/shimla.jpg"],
    guests: 3,
    bedrooms: 1,
    bathrooms: 1,
    description: "A cozy wooden retreat with pine views and fresh air.",
    isWishlisted: false,
    bhk: 1,
  },
  {
    id: 6,
    title: "Beach Hut in Andaman",
    location: "Andaman, India",
    price: 3500,
    images: ["/andaman.jpg"],
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    description: "Private beach hut just steps from turquoise water.",
    isWishlisted: false,
    bhk: 1,
  },
  {
    id: 7,
    title: "Mughal Era Stay in Agra",
    location: "Agra, India",
    price: 1600,
    images: ["/agra.jpg"],
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    description: "Peaceful studio with Taj Mahal view and rooftop dining.",
    isWishlisted: false,
    bhk: 1,
  },
  {
    id: 8,
    title: "Spiritual Cottage in Varanasi",
    location: "Varanasi, India",
    price: 1200,
    images: ["/varanasi.jpg"],
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    description: "Traditional stay near ghats, spiritual and soulful.",
    isWishlisted: false,
    bhk: 1,
  },
  {
    id: 9,
    title: "River View Camp in Rishikesh",
    location: "Rishikesh, India",
    price: 1000,
    images: ["/rishikesh.jpg"],
    guests: 3,
    bedrooms: 1,
    bathrooms: 1,
    description: "Adventure stay with river rafting and yoga sessions.",
    isWishlisted: false,
    bhk: 1,
  },
  {
    id: 10,
    title: "Lakehouse in Nainital",
    location: "Nainital, India",
    price: 2000,
    images: ["/nainital.jpg"],
    guests: 4,
    bedrooms: 2,
    bathrooms: 2,
    description: "Serene lake view cottage ideal for couples & families.",
    isWishlisted: false,
    bhk: 2,
  },
  {
    id: 11,
    title: "Royal Stay in Mysore",
    location: "Mysuru, India",
    price: 1700,
    images: ["/mysore.jpg"],
    guests: 3,
    bedrooms: 2,
    bathrooms: 1,
    description: "Stay near Mysore Palace with rich South Indian heritage.",
    isWishlisted: false,
    bhk: 2,
  },
  {
    id: 12,
    title: "sikkim",
    location: "Sikkim, India",
    price: 1400,
    images: ["/jammu.jpg"],
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    description: "Scenic, rocky landscape stay near ancient temples.",
    isWishlisted: false,
    bhk: 1,
  },
  {
    id: 13,
    title: "Road camp in ladakk",
    location: "Ladakk, India",
    price: 2200,
    images: ["/ladakk.jpg"],
    guests: 3,
    bedrooms: 2,
    bathrooms: 1,
    description: "Charming yellow bungalow in French quarter near beach.",
    isWishlisted: false,
    bhk: 2,
  },
  {
    id: 14,
    title: "Luxury Studio in Mumbai",
    location: "Mumbai, India",
    price: 2800,
    images: ["/mumbai.jpg"],
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    description: "Chic and compact with skyline view and great location.",
    isWishlisted: false,
    bhk: 1,
  },
  {
    id: 15,
    title: "Hilltop in Darjeeling",
    location: "Darjeeling, India",
    price: 1900,
    images: ["/darjeeling.jpg"],
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    description: "Peaceful home surrounded by tea gardens and Kanchenjunga views.",
    isWishlisted: false,
    bhk: 1,
  }
];



export const staycity = [
  { id: 1, name: "Goa", image: "/city/goa.jpg" },
  { id: 2, name: "Jaipur", image: "/city/jaipur.jpg" },
  { id: 3, name: "Manali", image: "/city/manali.jpg" },
  { id: 4, name: "Darjeeling", image: "/city/darjeeling.jpg" },
  { id: 5, name: "Rishikesh", image: "/city/rishikesh.jpg" },
  { id: 6, name: "ladakk", image: "/city/ladakk.jpg" },
];




export const faqItems = [
  {
    question: "How does the stay booking process work?",
    answer:
      "Browse through available stays, choose your preferred property, select the dates, and click 'Book Now'. Once confirmed, you'll receive all details via email.",
  },
  {
    question: "Can I search for stays using an image?",
    answer:
      "Yes! With our AI-powered image search, simply upload a photo of a property you like and we’ll find visually similar stays for you.",
  },
  {
    question: "Are all stays verified and trustworthy?",
    answer:
      "All listings go through a strict verification process to ensure safety, accuracy, and host credibility before appearing on our platform.",
  },
  {
    question: "What happens after I book a stay?",
    answer:
      "You'll receive a confirmation email with stay details, host contact, and check-in instructions. The host will also be notified to prepare for your arrival.",
  },
  {
    question: "Can I cancel or reschedule my booking?",
    answer:
      "Yes, most stays offer flexible cancellation policies. You can manage, modify, or cancel your bookings from your profile dashboard depending on the host’s policy.",
  },
];
